<a href="https://colab.research.google.com/github/IsWallison/WATER-SERVICES-AND-TECHNOLOGIES/blob/main/Analise_dos_dados_WATER_SERVICES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### **Analise dos dados de laudos Ambientais**
*WATER SERVICES AND TECHNOLOGIES*

*by [Wallison](https://www.linkedin.com/in/wallison-borges-48312516a/)*

Resumo:

Anexo a este documento, você recebeu uma planilha “PR2237068_laudo_1.xlsx” (A) representando um monitoramento ambiental de uma determina localidade; ela contém os resultados analíticos das amostras coletadas. A planilha foi gerada por um laboratório de análise em um layout próprio.

Recebeu também uma planilha adicional “20230701_valores_referencia.xlsx” (B) contendo os valores orientadores de uma legislação fictícia que deverão ser utilizados para comparação dos resultados analíticos contidos na primeira planilha.  

Exercício 1:
Transforme a planilha (A) em uma tabela em que cada coluna represente uma variável como no exemplo abaixo. Você pode utilizar uma nomenclatura diferente ou colunas adicionais se julgar necessário.
  
Fique atento para pontos como:

•	Colunas que podem ser removidas na transformação;

•	Colunas adicionais que podem ser adicionadas para facilitar análises futuras;

•	Tratamento de caracteres especiais;

•	Consistência e razoabilidade no tipo de dados em cada coluna;

•	Separadores decimais e de milhares;

•	Formato de data;


Para a transformação do arquivo, sugere-se utilizar o Power Query dentro do Excel ou linguagens de programação como Python e R.
Como entregável deste exercício, apresente um documento em Word ou PDF explicando sucintamente o raciocínio utilizado para transformar a tabela bem como possíveis inconsistências encontradas. Apresente também a tabela obtida na transformação e os códigos desenvolvidos caso utilize Python e/ou R.

In [101]:
# importar os pacotes necessários
import pandas as pd
import numpy as np
from google.colab import files

In [127]:
# importar os dados
df = pd.read_excel('/content/PR2237068_laudo_1.xlsx')
df_refer = pd.read_excel('/content/20230701_valores_referencia.xlsx')

## Análise Exploratória

In [128]:
#Visualização do dataset
df.head()

,Unnamed: 0,id parametro,grupo parametro,Lims Codigo,unidade,lim quant,PR2237068,PR2237068.1,PR2237068.2,PR2237068.3,PR2237068.4,PR2237068.5,PR2237068.6,PR2237068.7,PR2237068.8,PR2237068.9,PR2237068.10
0,id amostra lab,NaN,NaN,NaN,NaN,NaN,001,002,003,004,005,006,007,008,009,010,011
1,nome amostra,NaN,NaN,NaN,NaN,NaN,RO-J,BC8,BC2,BC4,BC3,BC14,BC11,BC15,BC17,BC6,AA02
2,ponto,NaN,NaN,NaN,NaN,NaN,PT-1,PT-1,PT-1,PT-1,PT-2,PT-2,PT-2,PT-2,PT-3,PT-3,PT-3
3,data coleta,NaN,NaN,NaN,NaN,NaN,20/04/2022,2022-05-20 00:00:00,2022-06-19 00:00:00,2022-07-19 00:00:00,2022-04-20 00:00:00,2022-05-20 00:00:00,2022-06-19 00:00:00,2022-07-19 00:00:00,20/04/2022,2022-05-20 00:00:00,2022-06-19 00:00:00
4,inicio profundidade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Conferência do nome de todas as colunas através do método columns.

In [129]:
df.columns

Index(['Unnamed: 0', 'id parametro', 'grupo parametro', 'Lims Codigo',
       'unidade', 'lim quant', 'PR2237068', 'PR2237068.1', 'PR2237068.2',
       'PR2237068.3', 'PR2237068.4', 'PR2237068.5', 'PR2237068.6',
       'PR2237068.7', 'PR2237068.8', 'PR2237068.9', 'PR2237068.10'],
      dtype='object')

A função "info()" é usada para obter informações gerais sobre um conjunto de dados, incluindo o número de linhas e colunas, o tipo de dados de cada coluna, a quantidade de valores não-nulos e memória usada.

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       50 non-null     object
 1   id parametro     44 non-null     float64
 2   grupo parametro  44 non-null     object
 3   Lims Codigo      44 non-null     object
 4   unidade          43 non-null     object
 5   lim quant        44 non-null     float64
 6   PR2237068        48 non-null     object
 7   PR2237068.1      48 non-null     object
 8   PR2237068.2      48 non-null     object
 9   PR2237068.3      48 non-null     object
 10  PR2237068.4      48 non-null     object
 11  PR2237068.5      48 non-null     object
 12  PR2237068.6      48 non-null     object
 13  PR2237068.7      48 non-null     object
 14  PR2237068.8      48 non-null     object
 15  PR2237068.9      48 non-null     object
 16  PR2237068.10     48 non-null     object
dtypes: float64(2), object(15)
memory usage: 6.8+ KB

A coluna 'id parâmetro' não agrega nenhuma informação, pois se trata de um identificador único. As colunas PR2237068n deverão ser modificadas futuramente. Farei uma cópia os dados do DataFrame original (df) para um novo DataFrame (df2).

In [132]:
#Novo dataframe
df2 =  df.copy()

#removendo a coluna "id parametro" pois não agrega em nada
df2.drop(columns='id parametro', inplace=True)
df2.head()

,Unnamed: 0,grupo parametro,Lims Codigo,unidade,lim quant,PR2237068,PR2237068.1,PR2237068.2,PR2237068.3,PR2237068.4,PR2237068.5,PR2237068.6,PR2237068.7,PR2237068.8,PR2237068.9,PR2237068.10
0,id amostra lab,NaN,NaN,NaN,NaN,001,002,003,004,005,006,007,008,009,010,011
1,nome amostra,NaN,NaN,NaN,NaN,RO-J,BC8,BC2,BC4,BC3,BC14,BC11,BC15,BC17,BC6,AA02
2,ponto,NaN,NaN,NaN,NaN,PT-1,PT-1,PT-1,PT-1,PT-2,PT-2,PT-2,PT-2,PT-3,PT-3,PT-3
3,data coleta,NaN,NaN,NaN,NaN,20/04/2022,2022-05-20 00:00:00,2022-06-19 00:00:00,2022-07-19 00:00:00,2022-04-20 00:00:00,2022-05-20 00:00:00,2022-06-19 00:00:00,2022-07-19 00:00:00,20/04/2022,2022-05-20 00:00:00,2022-06-19 00:00:00
4,inicio profundidade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Vou começar a mudar as colunas para adiantar e facilitar o projeto. rename() é a forma mais básico de renomear uma única coluna em um DataFrame do Pandas.

In [133]:
df2.rename(columns={'Unnamed: 0': 'Parametro Analisado'}, inplace=True)

Como foi solicitado que cada coluna represente uma variável, utilizei o código a seguir para selecionar as linhas com os valores referentes a datas, em seguida criei uma função para analisar se o valor era uma data, aproveitei e já salvei os valores do ponto e do nome da amostra no mesmo dicionário, ou seja, cada valor vai conter a data, ponto e nome da amostra. A última parte do código é um loop Renomear as colunas usando o mapeamento de datas, mantendo os nomes das colunas não relacionadas a datas. Antes algumas colunas se chamava de "PR2237068n", agora vai se chamar algo parecido com "2022-04-20|RO-J|PT-1".

In [134]:
#So vou pegar os valores referentes as datas
linha_selecionada = df.loc[3][6:]

# Função para verificar se um valor é uma data
def is_date(value):
    try:
        pd.to_datetime(value)
        return True
    except:
        return False
c = 6
# Percorrer as células da linha selecionada e criar o mapeamento
mapeamento_datas = {}
for idx, value in linha_selecionada.items():
    if is_date(str(value)):
        mapeamento_datas[idx] = str(pd.to_datetime(value).date()) + '|' + str(df.loc[1][c]) + '|' + str(df.loc[2][c])
        c+=1

# Agora 'mapeamento_datas' é um dicionário onde as chaves são os valores originais
# e os valores são as datas correspondentes (apenas a parte de data)

# Renomear as colunas usando o mapeamento de datas, mantendo os nomes das colunas não relacionadas a datas
novos_nomes_colunas = []
for coluna in df2.columns:
    if coluna in mapeamento_datas:
        novos_nomes_colunas.append(mapeamento_datas[coluna])
    else:
        novos_nomes_colunas.append(coluna)

# Atualizar os nomes das colunas no DataFrame
df2.columns = novos_nomes_colunas
df2.head()

<ipython-input-134-a776797f4650>:7: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  pd.to_datetime(value)
<ipython-input-134-a776797f4650>:16: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  mapeamento_datas[idx] = str(pd.to_datetime(value).date()) + '|' + str(df.loc[1][c]) + '|' + str(df.loc[2][c])

,Parametro Analisado,grupo parametro,Lims Codigo,unidade,lim quant,2022-04-20|RO-J|PT-1,2022-05-20|BC8|PT-1,2022-06-19|BC2|PT-1,2022-07-19|BC4|PT-1,2022-04-20|BC3|PT-2,2022-05-20|BC14|PT-2,2022-06-19|BC11|PT-2,2022-07-19|BC15|PT-2,2022-04-20|BC17|PT-3,2022-05-20|BC6|PT-3,2022-06-19|AA02|PT-3
0,id amostra lab,NaN,NaN,NaN,NaN,001,002,003,004,005,006,007,008,009,010,011
1,nome amostra,NaN,NaN,NaN,NaN,RO-J,BC8,BC2,BC4,BC3,BC14,BC11,BC15,BC17,BC6,AA02
2,ponto,NaN,NaN,NaN,NaN,PT-1,PT-1,PT-1,PT-1,PT-2,PT-2,PT-2,PT-2,PT-3,PT-3,PT-3
3,data coleta,NaN,NaN,NaN,NaN,20/04/2022,2022-05-20 00:00:00,2022-06-19 00:00:00,2022-07-19 00:00:00,2022-04-20 00:00:00,2022-05-20 00:00:00,2022-06-19 00:00:00,2022-07-19 00:00:00,20/04/2022,2022-05-20 00:00:00,2022-06-19 00:00:00
4,inicio profundidade,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

 Agora irei usar a função pandas.melt() para reformula DataFrame, também vou orderná-lo em relação à coluna "Parâmetro Analisado" e por fim vou remover algumas informações da coluna valor, como, por exemplo, "mg/L", pois essa informação já está presente na coluna "Unidade"

In [135]:
# Derreter as colunas de datas em uma coluna "data coleta"
df_melted_dates = df2.melt(id_vars=["Parametro Analisado", "grupo parametro",
                                    "Lims Codigo", "unidade", "lim quant"],
                                   value_vars=df2.columns[5:], # A partir da coluna PR2237068
                                   var_name="data coleta",
                                   value_name="valor")

# Filtrar as linhas em que a coluna "valor" não é vazia
df_melted_dates = df_melted_dates[df_melted_dates["valor"].notna()]

#Ordenar em ordem alfabetica
df_sorted = df_melted_dates.sort_values(by="Parametro Analisado")

#Remover mg/L"
df_sorted['valor'] = df_sorted['valor'].str.split(' ').str[0].str.strip()


df_sorted.head()

,Parametro Analisado,grupo parametro,Lims Codigo,unidade,lim quant,data coleta,valor
29,Alcalinidade em pH 4,Outros,W-ALK-PCT,mmol/L,0.15,2022-04-20|RO-J|PT-1,1.66
379,Alcalinidade em pH 4,Outros,W-ALK-PCT,mmol/L,0.15,2022-07-19|BC15|PT-2,2.60
479,Alcalinidade em pH 4,Outros,W-ALK-PCT,mmol/L,0.15,2022-05-20|BC6|PT-3,2.43
129,Alcalinidade em pH 4,Outros,W-ALK-PCT,mmol/L,0.15,2022-06-19|BC2|PT-1,<0.150
529,Alcalinidade em pH 4,Outros,W-ALK-PCT,mmol/L,0.15,2022-06-19|AA02|PT-3,4.25

Agora vou separar a coluna "data coleta" em três novas colunas: 'Data da Amostra', 'Nome da Amostra', 'Nome do Ponto', vou removê-la e aproveitar para transformar a nova coluna "Data da Amostra" no formato de data no padrão brasileiro.

In [136]:
#Divisão das colunas
df_sorted[['Data da Amostra', 'Nome da Amostra', 'Nome do Ponto']] = df_sorted['data coleta'].str.split('|', expand=True)

#Remoção da coluna
df_sorted = df_sorted.drop(columns='data coleta',axis=1)

#Converção do tempo
df_sorted['Data da Amostra'] = pd.to_datetime(df_sorted['Data da Amostra'])
df_sorted['Data da Amostra'] = df_sorted['Data da Amostra'].dt.strftime('%d/%m/%Y')

df_sorted.head()

,Parametro Analisado,grupo parametro,Lims Codigo,unidade,lim quant,valor,Data da Amostra,Nome da Amostra,Nome do Ponto
29,Alcalinidade em pH 4,Outros,W-ALK-PCT,mmol/L,0.15,1.66,20/04/2022,RO-J,PT-1
379,Alcalinidade em pH 4,Outros,W-ALK-PCT,mmol/L,0.15,2.60,19/07/2022,BC15,PT-2
479,Alcalinidade em pH 4,Outros,W-ALK-PCT,mmol/L,0.15,2.43,20/05/2022,BC6,PT-3
129,Alcalinidade em pH 4,Outros,W-ALK-PCT,mmol/L,0.15,<0.150,19/06/2022,BC2,PT-1
529,Alcalinidade em pH 4,Outros,W-ALK-PCT,mmol/L,0.15,4.25,19/06/2022,AA02,PT-3

Agora está na hora de começar a trabalhar com o segundo dataset (valores_referencia)

In [138]:
df_refer.head()

       codigo_parametro  valor_minimo  valor_maximo
0    Bario Total (mg/L)           NaN         1.000
1  Berilio Total (mg/L)           NaN         0.100
2     Boro Total (mg/L)           NaN         0.750
3   Cadmio Total (mg/L)           NaN         0.010
4   Chumbo Total (mg/L)           NaN         0.033

Não tenho muito o que fazer nesse dataset, vou apenas remover a unidade que estão dentre parêntesis, para ficar mais fácil de comparar os parâmetros entre os datasets.

In [140]:
# Remover o que esta dentro do parentesis '()'
df_refer_limpo = df_refer.copy()
df_refer_limpo['codigo_parametro'] = df_refer['codigo_parametro'].str.split('(').str[0].str.strip()

df_refer_limpo.head()

  codigo_parametro  valor_minimo  valor_maximo
0      Bario Total           NaN         1.000
1    Berilio Total           NaN         0.100
2       Boro Total           NaN         0.750
3     Cadmio Total           NaN         0.010
4     Chumbo Total           NaN         0.033

In [141]:
# Renomear para ficar mais facil uma vez que os nomes são diferentes
df_refer_limpo['codigo_parametro'] = df_refer_limpo['codigo_parametro'].replace(
    {'OD_in situ': 'Oxigenio Dissolvido','pH_in situ': 'pH',
    'Sulfeto_H2S nao dissoc': 'Sulfeto como H2S', 'Sulfato':'Sulfato como SO4--'}
     )

In [80]:
# Lista de nomes a serem verificados
nomes_a_verificar = df_refer_limpo['codigo_parametro'].unique()

# Criar listas para armazenar os nomes encontrados e não encontrados
nomes_encontrados = []
nomes_nao_encontrados = []

# Percorrer os nomes a verificar e verificar se estão na coluna 'Nome da Amostra'
for nome in nomes_a_verificar:
    if nome in df_sorted['Parametro Analisado'].values:
        nomes_encontrados.append(nome)
    else:
        nomes_nao_encontrados.append(nome)

# os nomes encontrados e não encontrados
print("Nomes encontrados:", nomes_encontrados, len(nomes_encontrados))
print("Nomes não encontrados:", nomes_nao_encontrados, len(nomes_encontrados))

Nomes encontrados: ['Bario Total', 'Berilio Total', 'Boro Total', 'Cadmio Total', 'Chumbo Total', 'Cobalto Total', 'Cromo Total', 'Fluoreto Total', 'Litio', 'Manganes Total', 'Nitrato como N', 'Nitrito como N', 'Oxigenio Dissolvido', 'pH', 'Prata Total', 'Selenio Total', 'Sulfato como SO4--', 'Sulfeto como H2S', 'Fosforo'] 19
Nomes não encontrados: ['Cianeto Livre', 'Cobre Dissolvido', 'Ferro Dissolvido', 'Mercurio Total', 'Niquel Total', 'Uranio Total', 'Vanadio Total', 'Zinco Total'] 19

In [142]:
nomes_nao_encontrados

['Cianeto Livre',
 'Cobre Dissolvido',
 'Ferro Dissolvido',
 'Mercurio Total',
 'Niquel Total',
 'Uranio Total',
 'Vanadio Total',
 'Zinco Total']

Percebi que alguns nomes estão com palavras diferentes, então resolvi pegar só o primeiro nome do elemento para fazer mais uma busca.

In [148]:
nomes_nao_encontrados_espaco = []
for i in nomes_nao_encontrados:
  nomes_nao_encontrados_espaco.append(i[:i.find(' ')])

# Lista de nomes a serem verificados

# Criar listas para armazenar os nomes encontrados e não encontrados
nomes_encontrados_segunda = []
nomes_nao_encontrados_segunda = []

# Percorrer os nomes a verificar e verificar se estão na coluna 'Nome da Amostra'
for nome in nomes_nao_encontrados_espaco:
    if nome in df_sorted['Parametro Analisado'].values:
        nomes_encontrados_segunda.append(nome)
        nomes_encontrados.append(nome)
    else:
        nomes_nao_encontrados_segunda.append(nome)

# Imprimir os nomes encontrados e não encontrados
print("Nomes encontrados:", nomes_encontrados_segunda)
print("Nomes não encontrados:", nomes_nao_encontrados_segunda)
print("Total de Nomes encontrados:",len(nomes_encontrados))

Nomes encontrados: ['Cobre', 'Ferro']
Nomes não encontrados: ['Cianeto', 'Mercurio', 'Niquel', 'Uranio', 'Vanadio', 'Zinco']
Total de Nomes encontrados: 27

A seguir renomeio algumas colunas e ordená-las, como não me foi dito como proceder, tomei a liberdade de excluir todos os dados referentes as amostras que não possuo parâmetros de referências, pois não teria como fazer nenhuma análise uma vez que não os possuo.

In [149]:
#Renomear as colunas
df_sorted.rename(columns={'Lims Codigo': 'Limite de Quantificacao',
                   'unidade':'Unidade','valor':'Valor'}, inplace=True)

#Ordenar as Colunas
df_sorted = df_sorted[['Nome do Ponto','Nome da Amostra','Data da Amostra','Parametro Analisado','Unidade','Limite de Quantificacao','Valor']]

In [150]:
# lista para armazenar os índices das linhas a serem mantidas
indices_a_manter = []

# loop sobre cada índice e valor da coluna 'Parametro Analisado'
for index, parametro in df_sorted['Parametro Analisado'].items():
    if parametro in nomes_encontrados:
        indices_a_manter.append(index)

# dataFrame com as linhas que devem ser mantidas
df_filtrado = df_sorted.loc[indices_a_manter]

df_filtrado

,Nome do Ponto,Nome da Amostra,Data da Amostra,Parametro Analisado,Unidade,Limite de Quantificacao,Valor
359,PT-2,BC15,19/07/2022,Bario Total,mg/L,W-METMSFL6,0.0272
209,PT-2,BC3,20/04/2022,Bario Total,mg/L,W-METMSFL6,0.0194
9,PT-1,RO-J,20/04/2022,Bario Total,mg/L,W-METMSFL6,0.0128
309,PT-2,BC11,19/06/2022,Bario Total,mg/L,W-METMSFL6,0.0265
109,PT-1,BC2,19/06/2022,Bario Total,mg/L,W-METMSFL6,0.0316
...,...,...,...,...,...,...,...
549,PT-3,AA02,19/06/2022,pH,NaN,W-PH-PCT,7.83
199,PT-1,BC4,19/07/2022,pH,NaN,W-PH-PCT,7.45
249,PT-2,BC3,20/04/2022,pH,NaN,W-PH-PCT,7.89
349,PT-2,BC11,19/06/2022,pH,NaN,W-PH-PCT,8.01
299,PT-2,BC14,20/05/2022,pH,NaN,W-PH-PCT,7.32

Vou renomear as colunas do segundo dataframe (valores de referência) para juntar os dois mais facilmente.

In [151]:
df_refer_limpo.rename(columns={'codigo_parametro': 'Parametro Analisado',
                   'valor_minimo':'Valor Minimo','valor_maximo':'Valor Maximo'},
                      inplace=True)
df_refer_limpo.head()

  Parametro Analisado  Valor Minimo  Valor Maximo
0         Bario Total           NaN         1.000
1       Berilio Total           NaN         0.100
2          Boro Total           NaN         0.750
3        Cadmio Total           NaN         0.010
4        Chumbo Total           NaN         0.033

Combinando os dois datasets baseando na coluna 'Parametro Analisado'

In [152]:
df_combinado = pd.merge(df_filtrado, df_refer_limpo, on='Parametro Analisado', how='inner')
df_combinado

,Nome do Ponto,Nome da Amostra,Data da Amostra,Parametro Analisado,Unidade,Limite de Quantificacao,Valor,Valor Minimo,Valor Maximo
0,PT-2,BC15,19/07/2022,Bario Total,mg/L,W-METMSFL6,0.0272,NaN,1.0
1,PT-2,BC3,20/04/2022,Bario Total,mg/L,W-METMSFL6,0.0194,NaN,1.0
2,PT-1,RO-J,20/04/2022,Bario Total,mg/L,W-METMSFL6,0.0128,NaN,1.0
3,PT-2,BC11,19/06/2022,Bario Total,mg/L,W-METMSFL6,0.0265,NaN,1.0
4,PT-1,BC2,19/06/2022,Bario Total,mg/L,W-METMSFL6,0.0316,NaN,1.0
...,...,...,...,...,...,...,...,...,...
204,PT-3,AA02,19/06/2022,pH,NaN,W-PH-PCT,7.83,6.0,9.0
205,PT-1,BC4,19/07/2022,pH,NaN,W-PH-PCT,7.45,6.0,9.0
206,PT-2,BC3,20/04/2022,pH,NaN,W-PH-PCT,7.89,6.0,9.0
207,PT-2,BC11,19/06/2022,pH,NaN,W-PH-PCT,8.01,6.0,9.0
208,PT-2,BC14,20/05/2022,pH,NaN,W-PH-PCT,7.32,6.0,9.0

Para fazer uma análise dos resultados, preciso transformar os valores da coluna resultado em números floats, mas percebi que alguns valores não estão preciso, por exemplo, alguns valores estão representados por um limite de detecção ou um valor abaixo do limite de quantificação em análises do laboratório (<0.050), optei por Substituir pelo Valor do Limite, no caso de <0.050, substitui por 0.050, que é o limite. Fiz uma função para tal propósito

In [155]:
def convert_limit(value):
    if isinstance(value, str) and value.startswith('<'):
        return float(value[1:])
    else:
        return float(value)

# Aplicar a função de conversão à coluna 'Valor'
df_combinado['Valor'] = df_combinado['Valor'].apply(convert_limit)

Resolvi criar uma nova coluna com as análises se os valores obtidos estão dentro dos valore mínimos e máximos, chamei a coluna de "Conformidade". Se os valores estiverem entre o mínimo e o máximo serão categorizados como "Conforme" caso contrário serão "Não Conforme".

In [156]:
df_combinado['Conformidade'] = (df_combinado['Valor'] >= df_combinado['Valor Minimo']
                                ) | (df_combinado['Valor'] <= df_combinado['Valor Maximo'])

# Substituir os valores na coluna 'Conformidade'
df_combinado['Conformidade'] = np.where(df_combinado['Conformidade'], 'Conforme', 'Não Conforme')
df_combinado

,Nome do Ponto,Nome da Amostra,Data da Amostra,Parametro Analisado,Unidade,Limite de Quantificacao,Valor,Valor Minimo,Valor Maximo,Conformidade
0,PT-2,BC15,19/07/2022,Bario Total,mg/L,W-METMSFL6,0.0272,NaN,1.0,Conforme
1,PT-2,BC3,20/04/2022,Bario Total,mg/L,W-METMSFL6,0.0194,NaN,1.0,Conforme
2,PT-1,RO-J,20/04/2022,Bario Total,mg/L,W-METMSFL6,0.0128,NaN,1.0,Conforme
3,PT-2,BC11,19/06/2022,Bario Total,mg/L,W-METMSFL6,0.0265,NaN,1.0,Conforme
4,PT-1,BC2,19/06/2022,Bario Total,mg/L,W-METMSFL6,0.0316,NaN,1.0,Conforme
...,...,...,...,...,...,...,...,...,...,...
204,PT-3,AA02,19/06/2022,pH,NaN,W-PH-PCT,7.8300,6.0,9.0,Conforme
205,PT-1,BC4,19/07/2022,pH,NaN,W-PH-PCT,7.4500,6.0,9.0,Conforme
206,PT-2,BC3,20/04/2022,pH,NaN,W-PH-PCT,7.8900,6.0,9.0,Conforme
207,PT-2,BC11,19/06/2022,pH,NaN,W-PH-PCT,8.0100,6.0,9.0,Conforme
208,PT-2,BC14,20/05/2022,pH,NaN,W-PH-PCT,7.3200,6.0,9.0,Conforme

Por fim o código para baixar o arquivo final em formato de xlsx.

In [28]:
df_combinado.to_excel('Analise_laudo_WATER_SERVICES.xlsx', index=False)
files.download('Analise_laudo_WATER_SERVICES.xlsx')